config/routes.rb
Rails.application.routes.draw do 
  root to: "admin/owners#index"
  
  %w[admin reports].each do |space|
    namespace space do
      resources :owners do
        resources :dogs
      end 
      resources :dogs, only: [:index, :show] do
        resources :meals
      end
    end 
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/owner.rb
class Owner < ApplicationRecord

    has_many :dogs, dependent: :destroy 

    has_one_attached :owner_image 

    validates :email, uniqueness: true 

    scope :active, -> { where(is_deleted: false) }

end

app/controllers/admin/owners_controller.rb
class Admin::OwnersController < ApplicationController
    before_action :find_owner, only: [:show, :edit, :update, :destroy]

    def index 
        # byebug
        @owners = Owner.active
    end 
    

    def show 
        @dogs = Dog.active
        @dogs = @dogs.select{|dog| dog.owner.id ===  @owner.id}
    end
    
    def new 
        @owner = Owner.new
    end 
  
    def create 
        @owner = Owner.create(owner_params)
        if @owner.valid? 
            redirect_to admin_owner_path(@owner) 
        else
            flash[:errors] = @owner.errors.full_messages 
            redirect_to new_admin_owner_path() 
        end  
    end 
    
    def edit 
    end 
    
    def update
        @owner.update(owner_params)
        if @owner.update(owner_params)
            redirect_to admin_owner_path(@owner.id) 
        else
            flash[:errors] = @owner.errors.full_messages 
            redirect_to  edit_admin_owner_path(@owner) 
        end  
    end 
    
    
  
    def destroy 
        # @owner.destroy 
        # byebug
        if @owner.update_attributes(is_deleted: true)
            @owner.dogs.each do |dog|
              dog.meals.update_all(is_deleted: true)
        end
        
            @owner.dogs.update_all(is_deleted: true)
        end
        redirect_to admin_owners_path
    end 

    private 

    def owner_params 
        params.require(:owner).permit(:first_name, :last_name, :email, :phone_number, :owner_image)
    end 

    def find_owner
        @owner = Owner.find(params[:id]) 
    end 
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
    before_action :find_owner, only: [:show, :edit, :update, :destroy]

    def index 
        @owners = Owner.all
    end 

    def show 
        @dogs = Dog.all.select{|dog| dog.owner.id ===  @owner.id}
    end
    
    def new 
        @owner = Owner.new
    end 
  
    def create 
        @owner = Owner.create(owner_params)
        if @owner.valid? 
            redirect_to owner_path(@owner) 
        else
            flash[:errors] = @owner.errors.full_messages 
            redirect_to new_owner_path() 
        end  
    end 
    
    def edit 
    end 
    
    def update
        @owner.update(owner_params)
        if @owner.update(owner_params)
            redirect_to owner_path(@owner.id) 
        else
            flash[:errors] = @owner.errors.full_messages 
            redirect_to edit_owner_path(@owner) 
        end  
    end 
  
    def destroy 
        @owner.destroy 
        redirect_to owners_path
    end 

    private 

    def owner_params 
        params.require(:owner).permit(:first_name, :last_name, :email, :phone_number, :owner_image)
    end 

    def find_owner
        @owner = Owner.find(params[:id]) 
    end 
end

app/controllers/reports/owners_controller.rb
class Reports::OwnersController < ApplicationController
    before_action :find_owner, only: [:show, :edit, :update, :destroy]

    def index 
        @owners = Owner.active 
    end 

    def show 
        @dogs = Dog.active 
        @dogs = @dogs.select{|dog| dog.owner.id ===  @owner.id}
    end
    
    private 

    def owner_params 
        params.require(:owner).permit(:first_name, :last_name, :email, :phone_number, :owner_image)
    end 

    def find_owner
        @owner = Owner.find(params[:id]) 
    end 
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/owners/_form.html.erb
<%= link_to "CANCEL!!!", owners_path %>

<% if flash[:errors] %>
    <% flash[:errors].each do |e| %>
        <%= e %>
    <% end %>
<% end %>

<%= form_for @owner do |f| %>
    <%= f.label :owner_image, "owner cover image" %>
    <%= f.file_field :owner_image %> <br>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %> <br>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %> <br>

    <%= f.label :email %>
    <%= f.text_field :email %> <br> 

    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %> <br>

    <%= f.submit %>
<% end %>

app/views/owners/index.html.erb
<div class="index-container">
    <%= button_to('Create New owner!', new_owner_path, method: :get ) %>

    
    <%  @owners.each do |owner| %>
    <div class="index-tile">
        <h2><%= link_to "more detail", owner %></h2>

        <% if owner.owner_image.attachment != nil %> 
            <h3><%= image_tag(owner.owner_image, class: "index-img") %></h3>  
            <h3>First Name: <%= owner.first_name %></h3> 
            <h3>Last Name: <%= owner.last_name %></h3> 
            <h3>Email: <%= owner.email %></h3> 
            <h3>Phone number: <%= owner.phone_number %></h3> 
        <% else %>
            <h3>First Name: <%= owner.first_name %></h3> 
            <h3>Last Name: <%= owner.last_name %></h3> 
            <h3>Email: <%= owner.email %></h3> 
            <h3>Phone number: <%= owner.phone_number %></h3> 
        <% end %>
        <%= button_to "Delete owner", owner_path(owner), method: :delete %>
        <%= button_to "Edit owner", edit_owner_path(owner), method: :get %>        
    </div>
    <%  end  %>
</div>

app/views/owners/show.html.erb
<div class="container">
    <div class="linkDivColorRed">
        <%= link_to "Go Home page", owners_path %>
    </div>
    <div class="linkDivColorGreen">
        <%= link_to "Add new dog", new_owner_dog_path({:owner_id => @owner.id}), method: :get  %>
    </div>
    <% if @owner.owner_image.attachment != nil %> 
        <h3><%= image_tag(@owner.owner_image, class: "index-img") %></h3>
        <h3> First Name: <%= @owner.first_name %></h3> 
        <h3> Last Name: <%= @owner.last_name %></h3> 
        <h3> Email: <%= @owner.email %></h3> 
        <h3> Phone number: <%= @owner.phone_number %></h3>
    <% else %>
        <h3> First Name: <%= @owner.first_name %></h3> 
        <h3> Last Name: <%= @owner.last_name %></h3> 
        <h3> Email: <%= @owner.email %></h3> 
        <h3> Phone number: <%= @owner.phone_number %></h3>
    <% end %>



    <%= link_to "Delete owner //", owner_path(@owner), method: :delete %>
    <%= link_to "Edit owner", edit_owner_path(@owner) %>
    
    <h4> DOGS OWNED </h4>
    <% @dogs.each do |dog| %>

        <% if dog.dog_image.attachment != nil %> 
            <h3><%= image_tag(dog.dog_image, class: "index-img") %></h3> 
            <h3> Name: <%= dog.name %></h3> 
            <h3> Age: <%= dog.age %></h3> 
            <h3> Color: <%= dog.color %></h3> 
            <h3> Weight: <%= dog.weight %></h3>    <%= link_to "more detail /// ", dog_path(dog) %>
        <% else %>
            <h3> Name: <%= dog.name %></h3> 
            <h3> Age: <%= dog.age %></h3> 
            <h3> Color: <%= dog.color %></h3>
            <h3> Weight: <%= dog.weight %></h3> 
   
            <%= link_to "more detail /// ", owner_dog_path({:owner_id => @owner.id, :id => dog.id}, method: :get) %>
        <% end %>

        <%= link_to "Delete dog////", dog_path(dog), method: :delete %>
        <%= link_to "Edit dog", edit_owner_dog_path({:owner_id => @owner.id, :id => dog.id}), method: :get  %>
    <% end %>
</div>