config/routes.rb
Rails.application.routes.draw do 
  root to: "admin/owners#index"
  
  %w[admin reports].each do |space|
    namespace space do
      resources :owners do
        resources :dogs
      end 
      resources :dogs, only: [:index, :show] do
        resources :meals
      end
    end 
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/dog.rb
class Dog < ApplicationRecord

  has_one_attached :dog_image 

  belongs_to :owner

  has_many :meals, dependent: :destroy

  scope :active, -> { where(is_deleted: false) }

end

app/controllers/admin/dogs_controller.rb
class Admin::DogsController < ApplicationController 
    before_action :find_dog, only: [:show, :edit, :update, :destroy]

    def index 
        @dogs = Dog.active
    end 
    
    def show 
        @meals = Meal.active
        @meals = @meals.select{|meal| meal.dog.id ===  @dog.id}
        # byebug
    end
    
    def new 
        @owner = Owner.find params[:owner_id]
        @dog = Dog.new(:owner_id=>@owner.id)
        @owner_id =  params[:owner_id].to_i
        # byebug
    end 
  
    def create 
        @dog = Dog.create(dog_params)
        @owner_id =  params[:dog][:owner_id].to_i
        # byebug
        if @dog.valid? 
            redirect_to admin_owner_path(@dog.owner.id) 
        else
            flash[:errors] = @dog.errors.full_messages 
            redirect_to  new_admin_owner_dog_path() 
        end  
    end 
    
    def edit 
        @owner_id = params[:owner_id].to_i
        # byebug
    end 
    
    def update
        if @dog.update(dog_params)
            redirect_to admin_owner_path(@dog.owner.id) 
        else
            flash[:errors] = @dog.errors.full_messages 
            redirect_to edit_admin_owner_dog_path(@dog) 
        end  
    end 
  
    def destroy 
        # @dog.destroy 
        if @dog.update_attributes(is_deleted: true)
            @dog.meals.update_all(is_deleted: true)
        end
        redirect_to admin_owner_path(params[:owner_id])
    end 

    private 

    def dog_params 
        params.require(:dog).permit(:name, :age, :color, :weight, :dog_image, :owner_id)
    end 

    def find_dog
        @dog = Dog.find(params[:id])
    end 
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController 
    before_action :find_dog, only: [:show, :edit, :update, :destroy]

    def index 
        @dogs = Dog.all
    end 
    
    def show 

        @meals = Meal.all.select{|meal| meal.dog.id ===  @dog.id}
        # byebug
    end
    
    def new 
        @dog = Dog.new
        @owner_id =  params[:owner_id].to_i
        # byebug
        @owners = Owner.all
    end 
  
    def create 
        @dog = Dog.create(dog_params)
        @owner_id =  params[:dog][:owner_id].to_i
        # byebug
        if @dog.valid? 
            redirect_to owner_dogs_path(@owner_id) 
        else
            flash[:errors] = @dog.errors.full_messages 
            redirect_to  new_owner_dog_path() 
        end  
        # redirect_to  @dog
    end 
    
    def edit 
        @owner_id = params[:owner_id].to_i
        # byebug
    end 
    
    def update
        if @dog.update(dog_params)
            redirect_to owner_dog_path(@dog) 
        else
            flash[:errors] = @dog.errors.full_messages 
            redirect_to edit_owner_dog_path(@dog) 
        end  
    end 
  
    def destroy 
        @dog.destroy 
        redirect_to dogs_path
    end 

    private 

    def dog_params 
        params.require(:dog).permit(:name, :age, :color, :weight, :dog_image, :owner_id)
    end 

    def find_dog
        @dog = Dog.find(params[:id]) 
    end 
end

app/controllers/reports/dogs_controller.rb
class Reports::DogsController < ApplicationController 
    before_action :find_dog, only: [:show, :edit, :update, :destroy]

    def index 
        @dogs = Dog.active
        @dogs = @dogs.order("owner_id ASC").order("age ASC")
    end 
    
    def show 
        @meals = Meal.active.order("updated_at ASC")
        @meals = @meals.select{|meal| meal.dog.id ===  @dog.id}
        # byebug
    end
    
    private 

    def find_dog
        @dog = Dog.find(params[:id])
    end 
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= link_to "CANCEL!!!", owners_path %>

<% if flash[:errors] %>
    <% flash[:errors].each do |e| %>
        <%= e %>
    <% end %>
<% end %>

<%= form_for @dog do |f| %>
    <%= f.hidden_field :owner_id, value: (@owner_id) %>

    <%= f.label :dog_image, "dog cover image" %>
    <%= f.file_field :dog_image %> <br>

    <%= f.label :name %>
    <%= f.text_field :name %> <br>

    <%= f.label :age %>
    <%= f.text_field :age %> <br> 

    <%= f.label :color %>
    <%= f.text_field :color %> <br> 

    <%= f.label :weight %>
    <%= f.text_field :weight %> <br>


    <%= f.submit %>
<% end %>

app/views/dogs/show.html.erb
<div class="container">
    <div class="linkDivColorRed">
        <%= link_to "Go Main page", dogs_path %>
    </div>
    <div class="linkDivColorGreen">
        <%= link_to "fed dog", new_dog_meal_path({:dog_id => @dog.id}), method: :get  %>
    </div>
    
    <% if @dog.dog_image.attachment != nil %> 
        <h3><%= image_tag(@dog.dog_image, class: "index-img") %></h3>  
        <h3> Name: <%= @dog.name %></h3> 
        <h3> Age: <%= @dog.age %></h3> 
        <h3> Color: <%= @dog.color %></h3> 
        <h3> Weight: <%= @dog.weight %></h3>
        <h3> Owner: <%= @dog.owner.first_name %></h3>
    <% else %> 
        <h3> Name: <%= @dog.name %></h3> 
        <h3> Age: <%= @dog.age %></h3> 
        <h3> Color: <%= @dog.color %></h3> 
        <h3> Weight: <%= @dog.weight %></h3>
        <h3> Owner: <%= @dog.owner.first_name %></h3>
    <% end %> 

    <%= link_to "Delete dog //", dog_path(@dog), method: :delete %>
    <%= link_to "Edit dog", edit_owner_dog_path({:owner_id => @dog.owner_id, :id => @dog.id}), method: :get  %>

    <h4> FED RECORD </h4>
    <% @meals.each do |meal| %>

    <h3>Brand: <%= meal.brand %></h3> 
    <h3>Quantity: <%= meal.quantity %></h3> 
    <h3>Finished: <%= meal.finished %></h3> 
    <h3>Finished on: <%= meal.finished_on %></h3>     <%= link_to "more detail /// ", dog_meal_path(meal) %>
    <%= link_to "Delete meal////", dog_meal_path(meal), method: :delete %>
    <%= link_to "Edit meal", edit_dog_meal_path(meal), method: :get %>
    <% end %>
    
</div>